"""add network to invoices

Revision ID: 24f90ba0d5a4
Revises: ddb37c3bee51
Create Date: 2026-07-13 11:08:34.599313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f90ba0d5a4'
down_revision: Union[str, Sequence[str], None] = 'ddb37c3bee51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network', sa.String(length=16), server_default='mainnet', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('network')

    # ### end Alembic commands ###
