"""add catalog hierarchy

Revision ID: 7c70b350e4c5
Revises: 6b54606645a0
Create Date: 2026-07-08 20:30:23.210410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c70b350e4c5'
down_revision: Union[str, Sequence[str], None] = '6b54606645a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_products_brand_id', 'brands', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_brand_id', type_='foreignkey')
        batch_op.drop_column('brand_id')

    op.drop_table('brands')
    op.drop_table('product_groups')
    op.drop_table('subcategories')
    op.drop_table('categories')
    # ### end Alembic commands ###
