"""add paid_asset paid_amount paid_fiat_rate to invoices

Revision ID: ddb37c3bee51
Revises: 184cdb4b32c5
Create Date: 2026-07-12 17:14:52.225721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb37c3bee51'
down_revision: Union[str, Sequence[str], None] = '184cdb4b32c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_asset', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('paid_amount', sa.Numeric(precision=18, scale=8), nullable=True))
        batch_op.add_column(sa.Column('paid_fiat_rate', sa.Numeric(precision=18, scale=8), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('paid_fiat_rate')
        batch_op.drop_column('paid_amount')
        batch_op.drop_column('paid_asset')

    # ### end Alembic commands ###
