"""make brand_id not null

Revision ID: eaa40357e5f7
Revises: 7c70b350e4c5
Create Date: 2026-07-08 20:38:56.025575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa40357e5f7'
down_revision: Union[str, Sequence[str], None] = '7c70b350e4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
